model:
  base_learning_rate: 1.0e-5
  target: ldm.models.autoencoder.VQNet
  params:
    monitor: val/total_loss
    embed_dim: 3
    n_embed: 8192
    image_key: target #image
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1,2,2,4]  # f = 2 ^ len(ch_mult)
      num_res_blocks: 1
      cond_type: max_cross_attn
      attn_type: max
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 0
    wrap: false
    train:
      target: datasets.dataset.Dataset
      params:
        dataroot:  "D:\\GMS\\UI-data\\UIEB_R90\\train"
        resolution: 256
        split: 'train'
        data_len: -1
        need_LR: False
    validation:
      target: datasets.dataset.Dataset
      params:
        dataroot:  "D:\\GMS\\UI-data\\UIEB_R90\\test"
        resolution: 256
        split: 'val'
        data_len: -1
        need_LR: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 8000
        val_batch_frequency: 800
        max_images: 1
        increase_log_steps: False
        log_images_kwargs: {'N': 1}

  trainer:
    benchmark: True
    max_epochs: -1
    gpus: 1
