model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusionUIE
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: target #image
    cond_stage_key: future_raw
    cond_key: input
    image_size: 16
    channels: 3
    cond_stage_trainable: False
    cross_mode: True
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 16 #8 # img size of latent, used during training, determines some model params, so don't change for inference
        in_channels: 6
        out_channels: 3
        model_channels: 256
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_max_self_attn: True # replace all full self-attention with MaxViT
    first_stage_config:
      target: ldm.models.autoencoder.VQNetInterface
      params:  #logs/VQ/checkpoints/epoch=000793.ckpt
        ckpt_path: "logs/VQ/checkpoints/epoch=000989.ckpt" # null # must specify pre-trained autoencoding model ckpt to train the denoising UNet
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: False
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 64
          ch_mult: [1,2,2,4]  # f = 2 ^ len(ch_mult)
          num_res_blocks: 1
          cond_type: max_cross_attn
          attn_type: max
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 0
    wrap: false
    train:
      target: datasets.dataset.Dataset #ldm.data.bvi_vimeo.BVI_Vimeo_triplet
      params:
        dataroot:  "D:\\GMS\\UI-data\\UIEB_R90\\train"  #"D:\\GMS\\UI-data\\UIEB_R90\\train"
        resolution: 256
        split: 'train'
        data_len: -1
        need_LR: False

    validation:
      target: datasets.dataset.Dataset #ldm.data.bvi_vimeo.BVI_Vimeo_triplet
      params:
        dataroot:  "D:\\GMS\\UI-data\\UIEB_R90\\test"  # "D:\\GMS\\UI-data\\UIEB_R90\\test" D:\GMS\UI-data\UIEB_R90\test\10
        resolution: 256
        split: 'val'
        data_len: -1
        need_LR: False


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1250
        val_batch_frequency: 125
        max_images: 2
        increase_log_steps: False
        log_images_kwargs: {'N': 1}

  trainer:
    benchmark: True
    max_epochs: -1
    gpus: 1
